### ISSUE TITLE
Use revparse to get a range of commits

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/git-churn#12]
We'd like to be able to parse an input string the same way that `git log` parses things. Use the docs for [gitrevisions](https://git-scm.com/docs/gitrevisions) for this. Hopefully we can use Git code to do this instead of implementing our own string parsing stuff.

The output of this would be a list of commits that are in that range.

**Comment by ashishgalagali** [comment]
Ref: https://github.com/src-d/go-git/issues/757#issuecomment-452697701
