### ISSUE TITLE
Initial go-git dependency setup

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/git-churn#3]
Set up the project so that we're using Go project conventions, and added go-git as a dependency. Do "something" with go-git. E.g. print out a diff for a commit.

**Comment by ashishgalagali** [comment]
Supported Capabilities by go-git
https://github.com/src-d/go-git/blob/master/COMPATIBILITY.md

**Comment by ashishgalagali** [comment]
Added functions to print the git branches and the last commit for a specified git directory. Printing out diff for a commit looked more complex to start with.
